### ISSUE TITLE
Working idea #1: Democratising citation and research annotation/evaluation

### ISSUE THREAD

**Issue by emmyft** [emmyft/mozfest19#2]
(This idea is moved here from README.md)

## Goals
* Encourage discussions around citation best practices
* Test out ideas of democratising citation/annotation/evaluation to get feedback
* Increase awareness of the issues surrounding current citation practices
* Can we use AI to help?

## What happens in the session (desperately need more ideas/refining)
* Introductory presentation (10 mins) - current practices
* A presentation/discussion on how AI can help? 

### random brainstorm of ideas
* Public annotation session – can we get the public to help fill in missing citations? (paper/software) if something like [this](https://www.biorxiv.org/content/10.1101/685263v1#comment-4524007465) could happen that would be amazing (scroll to the comments at the bottom)
* (an easier version of the above) Public annotation of the _context_ of the citation – participants to classify citations with emojis?
* Participant to understand what a citation is actually referring to (and how difficult it is to actually figure that out): give them a paragraph on a paper followed by the original article, ask them to find the corresponding bit of the cited paper that was actually cited.
* 

## post-mozfest idea
* Blog post on eLife Labs
* If we are actually user-testing a prototype/UI, we can further develop it
*

**Comment by emmyft** [comment]
Elaborating on this idea in response to #1 

A citation is a nod/reference to someone else's work. Inside and outside of science, there could be multiple reasons why you would refer to someone else's work:
* you reuse/built on top of their work and want to acknowledge it
* you like/dislike/agree with/disagree with it and would like to comment on it
* you want to share it
* your supervisor said you should cite their work

Somehow in science, a citation is always a good thing. IF is based on # citations, and research evaluation is based on IF. imo this shouldn't be the case. 
1. there needs to be at least a division between "endorsing" and "disagreeing" citations (remember the days when FB only had a "Like" button and the awkward moments when you had to "like" people's posts on e.g. natural disasters?)
2. on top of this "valence", maybe there also needs to be a "magnitude" aspect to a citation – did you reuse an entire piece of software, or did you simply refer to one sentence of a 38-page review?
3. who gets to decide on all of this? only the author, can readers disagree with citations/ suggest better citations / point out missing citations?
4. how can all this be factored into research evaluation?

So if we do go with this idea... the immediate goal is to loop more people into this discussion and raise awareness of the issues with the current system of citation and research evaluation (so the goal is to get people to understand the general ridiculousness of the current research evaluation system). If we end up with some sort of futuristic citation standard practice / system, that would be absolutely amazing.

The fear is that this is all too specific to research (hence decreasing participation from a broader audience), not related enough to openness, and also difficult to incorporate the AI theme. If we do want to appeal to a more general audience, we would need to come up with maybe some smart analogy.

**Comment by npscience** [comment]
Reading this, I'm thinking about a more general theme being the potential to over-interpret a highly simplified and ambiguous indicator (which is relevant to internet health)

e.g. pageviews (what does this really mean? should internet economics [read: advertising revenue] be built on site visibility? what's the alternative?)
e.g. twitter RTs (note how people now look at the ratio of likes:comments to pick out tweets that the network generally disagrees with -- high comment, low like)
e.g. citations (as you mention above), intended to be a measure of readership (before we had pageviews) of a container (journal) distilled in a kind of equation that is now used to measure prestige of an individual work.

I assume you've seen scite.ai --  might be interesting to explore their data, and look into how hard it is to interpret what a citation really means (my limited exploration == I'm most curious to find negative citations [because, gossip] but they are rare)

I'd love to hear answers to "why did you cite this?"

Finally, there's an interesting preprints angle here: debate between citing preprints as a scholarly object (because they've informed your thinking) versus reticence to cite the non-peer-reviewed version of literature (but note blogposts, webpages, etc can be cited) -- and I guess this loops back to Yo's examples: citation behaviour is learned, building new practice of citing software etc in an appropriate way takes time and learning too.

**Comment by emmyft** [comment]
closing this – probably not going forward with this idea (:
